DROP TABLE IF EXISTS DOCTORS CASCADE;

CREATE TABLE DOCTORS
(
    id         SERIAL PRIMARY KEY,
    department VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS PATIENTS CASCADE;

CREATE TABLE PATIENTS
(
    id         SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name  VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS DOCTORS_PATIENTS CASCADE;

CREATE TABLE DOCTORS_PATIENTS
(
    doctor_id  INT REFERENCES DOCTORS (id) ON UPDATE CASCADE,
    patient_id INT REFERENCES PATIENTS (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT DOCTORS_PATIENTS_PKEY PRIMARY KEY (doctor_id, patient_id)
);

DROP TABLE IF EXISTS DISEASES CASCADE;

CREATE TABLE DISEASES
(
    id         SERIAL PRIMARY KEY,
    patient_id INT         NOT NULL,
    disease    VARCHAR(50) NOT NULL,
    FOREIGN KEY (patient_id) REFERENCES PATIENTS (id)
);

DROP TABLE IF EXISTS DOCUMENT_REPORT CASCADE;

CREATE TABLE DOCUMENT_REPORT
(
    id              SERIAL PRIMARY KEY,
    execution_time  INT    NOT NULL,
    doctor_id       INT    NOT NULL,
    error           TEXT   NOT NULL,
    document_source VARCHAR(10) NOT NULL
);
