POST http://localhost:8080/api/save HTTP/1.1
Content-Type: application/json

{
  "id": "101",
  "department": "better",
  "patients": [
    {
      "id": "13",
      "first_name": "John",
      "last_name": "Smith",
      "diseases": [
        "nice_to_people",
        "long_legss"
      ]
    },
    {
      "id": "20",
      "first_name": "Marys",
      "last_name": "Novak",
      "diseases": [
        "used_to_have_dredds",
        "nice_to_people"
      ]
    },
    {
      "id": "30",
      "first_name": "Alice",
      "last_name": "Woods",
      "diseases": [
        "chocaholic",
        "great_haircut"
      ]
    }
  ]
}